apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: com-clean-dev
data:
  my.cnf: |
    [mysqld]
    max_connections = 300
    innodb_buffer_pool_size = 256M
    # add more settings as needed
